### ISSUE TITLE
[Feature Request] Access to home-folder

### ISSUE THREAD

**Issue by toby63** [flathub/info.mumble.Mumble#14]
A user reported on mumble issues (https://github.com/mumble-voip/mumble/issues/4176), that he is not able to access the mumble folders to 
> copy or move the audio files from it.

I found out that this is intended by flatpak by default, but that there are options available to change it.

He solved the problem by changing the flatpak config with:
`sudo flatpak override info.mumble.Mumble --filesystem=home`

I can't assess the situation, because I don't use a flatpak package, but if this is a problem for accessing audio recordings or changing mumble skins for example, you might consider applying a general change to the flatpak package or (if possible) add a notice about this somewhere; act as you see fit :slightly_smiling_face:.

I only wanted to report this just in case someone is searching for solutions.

**Comment by JBBgameich** [comment]
hi, thanks for reporting the issue. Granting access to the home directory should ideally be avoided in flatpaks, but it is fine for me at least as an intermediate workaround.

@Krzmbrzl I'm not sure how feasible that is for Mumble, but apps should usually apps should request access to only the file it needs to write to, by opening a save dialog. This way access to the home directory can be avoided.

**Comment by Krzmbrzl** [comment]
I'm actually not familiar with how the recording stuff works but from a quick glance we allow the user to use placeholders for specifying save-path and/or file names. I guess that during that process there's also a part where it wants to expand a placeholder for the home directory or something like that...

I'm not sure though. In case you're interested, this seems to be the relevant file: https://github.com/mumble-voip/mumble/blob/master/src/mumble/VoiceRecorderDialog.cpp

**Comment by toby63** [comment]
As far as I understand it, this is not only about audio recording, there might be other cases (like changing mumble skin, copy config etc.) for accessing the mumble folder and copy/cut/move something.
I don't know though whether that really applies :shrug:.

Maybe there already is a solution inside flatpak, so that users can access the internal flatpak folders :thinking:, but given that the user from the issue was not able to copy it, it is maybe not so easy/handy/obvious.

Maybe a solution could be to just give the flatpak the specific mumble path...but I don't know how mumble is creating this path.

From: https://docs.flatpak.org/en/latest/sandbox-permissions.html
```
--filesystem=/path/path - access specific paths
--filesystem=xdg-download - access a specific XDG folder
```

**Comment by JBBgameich** [comment]
I applied a patch to allow home access a few hours ago, but unfortunately the stable version of mumble that is packaged currently can not be built from git anymore, since one of the submodule hosts appears to be down.

The error reported on the build server is
```
fatal: unable to access 'https://git.xiph.org/celt.git/': Failed connect to git.xiph.org:443; Connection refused
```

https://github.com/mumble-voip/mumble/commit/a642894f4a4417f6bbe35fb1344e66dc7e8f5481 seems like the correct fix for it, but I can't cherry-pick this patch since flatpak-builder first tries to check out the submodules and then applies the patch files.
The only possible way to fix it I see right now is to package the rc-release, but that could introduce other issues. If there is a release tarball containing those submodules, that could be used as well.
What would you as a mumble developer prefer here @Krzmbrzl?

**Comment by toby63** [comment]
@JBBgameich 
I see two options for you:
1. Wait until 1.3.1 is released (will be very soon as far as I know)
2. fork mumble, apply the patch and use that as a source for the build

**Comment by Krzmbrzl** [comment]
@JBBgameich I think that's the issue I fixed with https://github.com/mumble-voip/mumble/commit/a56e57cf9ca5613aae54444b0d2b8ae20716286f

I have also backported that commit to 1.3.x: https://github.com/mumble-voip/mumble/commit/1b6fa82e36d952dfb2afaa7d20884c54842df76d

Thus you could either cherry-pick that commit onto the 1.3.0 state or indeed already package 1.3.1.rc.
I think personally I'd think the cleaner solution would be to keep providing 1.3.0 until we release 1.3.1 officially. On the other hand our plan was to do that in the coming days, so it might not matter all that much (but then again we wanted to release it "in the coming days" for a few days now already, so I guess this statement is not super accurate) :shrug:
