### ISSUE TITLE
mumble-overlay can't find libmumble.so.1

### ISSUE THREAD

**Issue by TheMadman** [flathub/info.mumble.Mumble#9]
Line 13 of the `bin/mumble-overlay` script searches the following paths for `libmumble.so.1`:
```
/lib /usr/lib /usr/lib/mumble /usr/lib32 /usr/lib32/mumble /usr/lib64 /usr/lib64/mumble
```

Because the path of `libmumble.so.1` is `/lib/mumble`, it isn't found when executing:

`flatpak run --command=mumble-overlay info.mumble.Mumble [executable]`

**Comment by JBBgameich** [comment]
While this is something that is fixable, from your explanation it sounds like the mumble-overlay works as a wrapper for other executables, maybe using LD_PRELOAD?
Due to flatpak sandboxing this would only work for apps included in the mumble flatpak, so realistically for no app at all.

Plesse tell me in case this understanding of mumble-overlay is wrong.

**Comment by TheMadman** [comment]
Yeah, Mumble's approach is to find 32-bit/64-bit `libmumble.so.1` libraries and add them to LD_PRELOAD based on the application being executed.

I'm not familiar enough with Flatpak's sandboxing to comment so I'll defer to you on that point.

**Comment by JBBgameich** [comment]
Seems like my initial comment applies, feel free to re-open if this is not true.
